services:

  home:
    build: ./home
    ports:
      - "8080:80"
    depends_on:
      - mediciones
      - monitoreo

  mediciones:
    build: ./mediciones
    ports:
      - "5001:5001"

  monitoreo:
    build: ./monitoreo
    ports:
      - "5002:5002"
    environment:
      - MEDICIONES_URL=http://mediciones:5001
    depends_on:
      - mediciones

  simulador:
    build: ./simulador
    environment:
      - MEDICIONES_URL=http://mediciones:5001
      - INTERVALO_SEGUNDOS=5
    depends_on:
      - mediciones